### ISSUE TITLE
atom php-cs-fixer not working

### ISSUE THREAD

**Issue by galbangi** [pfefferle/atom-php-cs-fixer#1]
i am getting this error
'php /usr/local/bin/php-cs-fixer fix' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

i check my path with which php-ca-fixer
/usr/local/bin/php-cs-fixer

i am new to atom please help me fix that thanks

**Comment by pfefferle** [comment]
galbangi I also have this problem from time to time with several plugins that are using command line tools. Have you tried it without `php`?

``` sh
/usr/local/bin/php-cs-fixer
```

**Comment by galbangi** [comment]
that works @pfefferle  thanks for help
