### ISSUE TITLE
No parsing on Windows

### ISSUE THREAD

**Issue by rugk** [pfefferle/atom-php-cs-fixer#10]
So hallo erst mal... :smile: 

No just joking, let's switch back to English: I've already replied in #6, but I think it's better to open a new issue about this so I can be sure everyone notices this.

In my case it still does not work in Atom, but if I call it manually...

See the gif for details:
![php-cs-fixer_notworking](https://cloud.githubusercontent.com/assets/11966684/9233357/dd430048-4132-11e5-9667-03cb92ca0cb1.gif)

Windows 7
2.3.0
Atom 1.0.6

**Comment by rugk** [comment]
@pfefferle Somebody there?

I've also another (possibly related problem). It seems there is a problem when loading libraries. It also shows a custom library I added and it shows me:

```
Warning: PHP Startup: Unable to load dynamic library 'D:\XAMPP\php\ext\php_<file>.dll' - Das angegebene Modul wurde nicht gefunden.
```

But in fact the DLL file exists and if I start php manually it does not show this message.
So I assume some environment variables are not set, because I get the same error if I execute php without the xampp_shell.bat.

**Comment by pfefferle** [comment]
Hmm, strange... I have tested it with Windows and XMPP and it worked... Will check my settings tomorrow and will post it here...

**Comment by pfefferle** [comment]
hey @rugk 

I have tested it with several settings and it seems to work always:
- with empty PHP executable path
- using php.exe without path
- using php.exe with path

You can try one more thing: Hit the right button on the `.phar` file and select "open with" and choose `PHP.exe` and try it once again.

**Comment by pfefferle** [comment]
...also try to use slashes `/` instead of backslashes `\` in the paths.

**Comment by rugk** [comment]
[Deleted this part as it's just confusing. Was just some debugging stuff on my side, which has nothing to do with this package]

I tried both things you suggested but it did not work.

**Comment by rugk** [comment]
So I've modified the package to add -vvv for debugging (maybe with a (user-friendly) setting this would also be an idea to add to the package) and executed it like this.

And indeed it returned 'invalid' (the `I` in the first line):

```
I
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixing time per file:
[0.020 s] D:\XAMPP\phplib\Foo.php

Fixed all files in 0.020 seconds, 4.000 MB memory used
```

But executing it on the command line works and just returns this:

```
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E
-error
   1) D:\XAMPP\phplib\Foo.php (blankline_after_open_tag, single_line_after_impor
ts, operators_spaces, psr0, line_after_namespace, braces)
Fixing time per file:
[0.152 s] D:\XAMPP\phplib\Foo.php

Fixed all files in 0.152 seconds, 4.750 MB memory used
```

**Comment by rugk** [comment]
I've tried it several times now and the result is always the same. (Except that now Atom refuses to reload the changed file if I fix it with the command line, but this of course does not have to do with this package)

**Comment by rugk** [comment]
Okay, I think I come closer: When I do not run the fix from the XAMPP shell, but use a normal CMD window I've get the same error.

So I tried to change the current directory to the PHP directory and executed the same command again. And... it worked. :smiley: 

So I think that's what you have to do. (don't know why CS fixer otherwise thinks the file is invalid - possibly because PHP throws the error with my added library, which it tries to load but [somehow] cannot find if the dir is wrong)

**Comment by pfefferle** [comment]
Can you write that in a short chapter so I can add it to the readme? I think that also might help others ;)

**Comment by pfefferle** [comment]
I am no Windows user so I am not very helpful with this ;)

**Comment by rugk** [comment]
Well... I have not solved it. It was just an demonstration of the issue.

I mean you would have to add some code which changes the dir before the php cs fixer is executed.
I don't know if you can do this in JS in Atom so easily. Possibly you have to temporary change it and change it back after execution.
Or you could also try to add the PHP dir to the PATH environment variable (only modified inside of Atom) which would have the same effect.
Possibly I could of course also write a workaround to explain the user possibly has to add the php dir to PATH variable globally, so for all processes, but the other solutions would be better IMO as they do not affect the whole system.

**Comment by pfefferle** [comment]
Hmm, I have tried it in a VirtualBox with Windows 8.1 and the latest XAMPP without any problems... Will try it again tomorrow to be sure though...

**Comment by rugk** [comment]
I already said that it may have to do with the PHP library (DLL) I added.
So unless you use this PHP may not throw an error always when cs-fixer tries to parse the scripts.

**Comment by rjv** [comment]
I'm encountering the same issue -- works fine via command line but no luck from Atom.

**Comment by rugk** [comment]
Okay, I added a small guide in #14.

**Comment by rjv** [comment]
@rugk I do have the php executable in my PATH - so I don't think that's my issue. Have a look at this screenshot from my dev tools console when I run the "fix" command:

![screenshot at 103434](https://cloud.githubusercontent.com/assets/532439/9935969/c1885482-5d27-11e5-8922-15467a75751b.png)

I'm not entirely sure what the third log item is telling me. Any insights?

**Comment by pfefferle** [comment]
Can you try to add the full path to your php executable or use `php.exe` instead of only `php`?

**Comment by rjv** [comment]
@pfefferle I tried both, here is the console output:
![screenshot at 110623](https://cloud.githubusercontent.com/assets/532439/9936912/363d8578-5d2c-11e5-83c1-17041b57374f.png)
Looks like the same result.

**Comment by rugk** [comment]
> I do have the php executable in my PATH

You mean the dir of the PHP executable? As this was the thing which solved the problem in my case.

**Comment by rjv** [comment]
@rugk Yes, that's correct - I meant the path to the executable. I have _C:\php_ (the location where php.exe lives) in the PATH.

**Comment by h7896v7347** [comment]
@rjv 
Try to change path to php-cs-fixer
Works:
C:\Users\Username\AppData\Roaming\Composer\vendor\ **fabpot\php-cs-fixer\php-cs-fixer**
Not working:
C:\Users\Username\AppData\Roaming\Composer\vendor\ **bin\php-cs-fixer**

**Comment by rjv** [comment]
@h7896v7347 Thank you for the recommendation. Switching the path to the fabpot directory did the trick. :+1:

**Comment by rugk** [comment]
@h7896v7347 @rjv
Maybe add this to the Readme?

**Comment by nahuelhds** [comment]
I came here to comment what @h7896v7347 just did.

Using **C:\Users\USERNAME\AppData\Roaming\Composer\vendor\fabpot\php-cs-fixer\php-cs-fixer** makes this work on Windows. This is because "php-cs-fixer" in PATH from Composer points to "_C:\Users\USERNAME\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat_" which is a bat, and when php runs it just can't interprete it (even the php-cs-fixer exists in the same dir, but Windows reads the bat first).

**C:\Users\USERNAME\AppData\Roaming\Composer\vendor\fabpot\php-cs-fixer\php-cs-fixer is the phar** itself and that's why it works.

**Comment by nahuelhds** [comment]
@pfefferle, I think you should add @h7896v7347 comment to the windows readme section. When you install with composer globally the PATH points to the bin folder which contains a bat file and not the phar which is where @h7896v7347 wrote.

Thanks!

**Comment by pfefferle** [comment]
will close this for now.
