### ISSUE TITLE
Add .php_cs search and passing as --config-file 

### ISSUE THREAD

**Issue by rugk** [pfefferle/atom-php-cs-fixer#11]
In the doc of PHP coding style fixer it says you can use the config file .php_cs "in the root directory of your project". However I assume php-cs-fixer itself only searches in the dir where the php file it checks is.
But as Atom can detect repos and open projects (directories) I think you could add a search for .php_cs (in the top-dir at least).

**Comment by pfefferle** [comment]
Oh, thanks for the tipp... Never heard/read about that before!

**Comment by rugk** [comment]
What does this closing mean? You do not implement it?

If not you should leave the issue open until it's implemented. (it would also confuse the milestone system otherwise)

**Comment by pfefferle** [comment]
no, it means that I have implementied it! will release the update soon!

**Comment by rugk** [comment]
Ah so just the release wasn't out. Okay, so that's great. :+1:
