### ISSUE TITLE
gif shows features not in this package

### ISSUE THREAD

**Issue by Marv51** [pfefferle/atom-php-cs-fixer#13]
This is a screenshot from the readme gif:
<img width="808" alt="screenshots 7" src="https://cloud.githubusercontent.com/assets/471338/9704710/5999f1de-54b0-11e5-93a8-1dcf3d22f79a.png">
The features I circled in green, are not available in my installation of the package. I looked through the code and I can not find anything in this package that could create these features. 

Are you using an other package to create these warnings or am I missing something?

**Comment by pfefferle** [comment]
Sorry, I forgot to deactivate all other plugins, before making that gif. This is not part of the fixer plugin, it is the [PHP-CS linter](https://atom.io/packages/linter-phpcs).
