### ISSUE TITLE
Unable to load php-cs-fixer installed via Composer on OSX

### ISSUE THREAD

**Issue by clemf** [pfefferle/atom-php-cs-fixer#15]
Hi, I have php-cs-fixer installed using `composer global require` like it says in the readme. It is in the default directory listed under the executable path setting. However, when I try to run the plugin I see this in the javascript console:

```
php-cs-fixer Command php
php-cs-fixer.coffee:81 php-cs-fixer Arguments ["~/.composer/vendor/bin/php-cs-fixer", "fix", "/Users/clemfreeman/Code/doctrine2tutorial/bootstrap.php", "--level=psr2"]
php-cs-fixer.coffee:83 Could not open input file: ~/.composer/vendor/bin/php-cs-fixer

php-cs-fixer.coffee:85 php exited with code: 1
```

The executable is there:

```
FM-clefre-Mac:bin clemfreeman$ pwd
/Users/clemfreeman/.composer/vendor/bin
FM-clefre-Mac:bin clemfreeman$ ls -la
total 16
drwxr-xr-x   4 clemfreeman  staff  136 Sep 15 14:22 .
drwxr-xr-x  12 clemfreeman  staff  408 Sep 15 14:22 ..
lrwxr-xr-x   1 clemfreeman  staff   35 Sep 14 14:01 php-cs-fixer -> ../fabpot/php-cs-fixer/php-cs-fixer
```

I haven't tried installing it via Homebrew but I would prefer not having to do that. Any idea what's going on?

**Comment by clemf** [comment]
I fixed the problem after a long time of pulling my hair out. It turns out that despite php-cs-fixer being available in my shell, the PATH environment variables were not being passed to Atom. I re-copied the recommended settings into my .zshrc file and it worked. You might want to make clear in your readme that you have to add the PATH settings to your shell to get php-cs-fixer working properly.

**Comment by pfefferle** [comment]
Sorry for the late reply! An alternative (an even simpler way) might be to add the full path to your php "executable".

**Comment by mauricio-masias** [comment]
IF you installed using composer: e.g. 
> composer global require friendsofphp/php-cs-fixer

Just add this
> export PATH="$PATH:$HOME/.composer/vendor/bin" 
on your terminal
