### ISSUE TITLE
Show notification if fixing fails

### ISSUE THREAD

**Issue by rugk** [pfefferle/atom-php-cs-fixer#17]
If there is a PHP syntax error fixing fails silently (`php-cs-fixer` just displays a list without any files it fixed). I think (at least when the setting in #12 is enabled) it should show an error in this case.

What could make this difficult is that if `php-cs-fixer` has nothing to fix it displays exactly the same output, so you don't really whether something nothing was fixed or there was a parsing error.

**Comment by pfefferle** [comment]
I tried to implement this in the latest version
