### ISSUE TITLE
php-cs-fixer not working with your plugin

### ISSUE THREAD

**Issue by ibnbd** [pfefferle/atom-php-cs-fixer#19]
I installed everything as you mentioned. I am using OS X 10.11 with homebrew 
php-cs-fixer working perfect from terminal but not working with your plugin.

**Comment by IsraelOrtuno** [comment]
Same here. I have installed it with composer and does not. 10.11 as well.

**Comment by pfefferle** [comment]
have you tried to add the full path to your composer file in the plugin settings?

```
/Users/<username>/.composer/vendor/bin/php-cs-fixer
```

**Comment by IsraelOrtuno** [comment]
I have just updated it to `/usr/local/bin/php-cs-fixer` and works pretty good

**Comment by darianbr** [comment]
Doesn't seem to be working for me either. I have full path to the fixer `/Users/darianbr/bin/php-cs-fixer` at version 1.10.2.

The project has a `.php_cs` file and this plugin notifies me that it's loading that config file.

I am on OSX 10.11.

Edit: Issue may be with the latest version of php-cs-fixer. I updated php-cs-fixer at the same time I installed this plugin. Now php-cs-fixer isn't even working when i run the command manually.

**Comment by JeffreyHyer** [comment]
:+1:

Had the same issue, changed the executable path in Atom Settings to full path (i.e. /Users/[username]/.composer/vendor/bin/php-cs-fixer instead of ~/.composer/...) and it fixed the issue.

OS X 10.11.1 fresh install on latest Atom (v1.3.1) with latest php-cs-fixer (v1.11)

**Comment by pfefferle** [comment]
Seems to work for everyone, so I will close this for now.
