### ISSUE TITLE
Problem with fixer file

### ISSUE THREAD

**Issue by tjapro** [pfefferle/atom-php-cs-fixer#22]
Hello!

After installed globally the php-cs-fixer and the plugin for atom I get this message:
`Could not open input file: ~/.composer/vendor/bin/php-cs-fixer`
What is the problem with the installation?
I'm in Fedora 23.

**Comment by pfefferle** [comment]
This is my fault, the demo path (user folder) is not working. Try the complete path `/home/<username>/.composer/vendor/bin/php-cs-fixer` or only `php-cs-fixer` if you have added it to your `PATH`

**Comment by pfefferle** [comment]
Will change the default value for the next release.

**Comment by tjapro** [comment]
Thank you!
I update the path and the plugin worked very well.
I have got an error message, but it is because I have xDebug on in composer.
Thanks!
