### ISSUE TITLE
Classes Names goes to lowercase

### ISSUE THREAD

**Issue by tjapro** [pfefferle/atom-php-cs-fixer#23]
Hello.
When I save a php file the name's classes goes to lowercase.
E.g.:
`class Foo_Bar extends Bar{}` goes to `class foo_bar extends Bar{}`
What happens here?

**Comment by pfefferle** [comment]
Sounds like a PHP-CS-Fixer "feature". Is the name of the file `foo_bar.php` (lowercase)?

**Comment by tjapro** [comment]
The name file is `home.php` and the code inside is
`
class controller_home extends Controller
{...}
`

**Comment by pfefferle** [comment]
And the file is in a `controller` folder?

Have a look at the ['fixers'](http://cs.sensiolabs.org/#usage):

> **psr0 [PSR-0]**
> Classes must be in a path that matches their namespace, be at least one namespace deep, and the class name should match the file name.

**Comment by pfefferle** [comment]
If you rename file and folder to uppercase it should work fine.

**Comment by tjapro** [comment]
I understand this rule, but I'm using a framework. I cannot change the folder/file structure.
Have anything that can I do or the only option is desactivate this atom plugin?

**Comment by pfefferle** [comment]
You can temporarily disable the auto save (perhaps I should think about a config file to enable/disable the settings project depending) or you can experiment with a [config file](https://mattstauffer.co/blog/using-php-cs-fixer-to-fix-up-your-php-code#saving-configuration) and some custom fixers. You can find a demo in the [examples folder](https://github.com/pfefferle/atom-php-cs-fixer/blob/master/examples/.php_cs).

**Comment by pfefferle** [comment]
BTW: the plugin supports `.php_cs` files in any subfolder, so you can define custom rules depending on folder structures.

**Comment by tjapro** [comment]
Thank you!

**Comment by pfefferle** [comment]
Let me know if you find a good solution to disable the plugin for certain projects/folders... perhaps it might be helpful to add informations like that to the FAQs...

**Comment by tjapro** [comment]
Maybe one of the following options:
- A field in the settings with the disabled projects/folders;
- A .fixer file in the root of the project folder with specific settings/options.
  What do you think?

**Comment by eriksape** [comment]
Maybe taking the config from the composer.json

For example in Laravel 5 places everything in the app/ folder but declares the App namespace for autoloading purposes in the composer.json file.

```

 {
        "psr-4": {
            "App\\": "app/",
        }
}

```

**Comment by eriksape** [comment]
in the .php_cs you can put disable psr0

```
fixers([
            '-psr0',
        ])
```

in the root of the project, that solve the problem with the namespaces
