### ISSUE TITLE
v2.5.6 - Doesn't work for larger files, keeps reporting "fixed file"

### ISSUE THREAD

**Issue by nanohard** [pfefferle/atom-php-cs-fixer#24]
Sometimes this plugin doesn't work for me. It reports via the pop-up that it fixed the code, but nothing changes and I can run it again and it reports the same thing (rather than reporting "Nothing to fix"). I'm working with PHP code in .htm files; I swear that it worked for one file then stopped working. All file permissions are the same (755) owned by my user and my user's primary group.

Just did some more testing, and it seems the size of the file is the cause. It doesn't seem to work on larger files, or works when it wants to on larger files. So far, "large file" can be defined as 600 lines of code, 21.1KB.

Debian Jessie (8.3) x64
Atom 1.5.3
atom-php-cs-fixer 2.5.6

Style: psr2
Fixers: none
##### Update

Tested php-cs-fixer by running it manually with this command:

```
php-cs-fixer fix /path/to/file --level=psr2
```

and it worked, so it's not an upstream problem with php-cs-fixer.
##### Update 2

I believe it to be a clash with saving the file, somehow.
The below situations are with "run-on-save" turned off, so I'm only using the keyboard shortcut ctrl+cmd+s.

Situation: File has been modified, but not saved.
Run php-cs-fixer (atom package): "Your code looks perfect... nothing to fix!"
Expected behavior: php-cs-fixer was expected to fix the file.
Actual behavior: Nothing.

Situation: File has been modified and saved.
Run php-cs-fixer (atom package): "Fixed file..."
Expected behavior: file marked as modified (according to the little dot next to filename in the tab's title).
Actual behavior: file not marked as modified, but it fixes the file.

So when I modify a file, I must save it twice if I want php-cs-fixer (atom-package) to run with "run-on-save". I've confirmed that saving it twice does actually save the file to how it looks in Atom.
I think this is related to #20 
Based on the limited code this plugin uses, it may be an upstream Atom problem. But I'm thinking that this plugin doesn't use the cached (modified) file; rather, it runs on the file saved to disk.
@pfefferle : Any chance to have this plugin work on the cached file, so that pressing save once will do the job?

**Comment by pfefferle** [comment]
can you send me an example `.htm` file?

**Comment by pfefferle** [comment]
Is this still a problem?

**Comment by pfefferle** [comment]
will close this for now, please reopen if it is still a problem!
