### ISSUE TITLE
xdebug warning

### ISSUE THREAD

**Issue by cxbig** [pfefferle/atom-php-cs-fixer#27]
On my local environment, `xdebug` is loaded always. 
It brings a problem:
`You are running php-cs-fixer with xdebug enabled. This has a major impact on runtime performance.`
Is it possible to add a parameter `-n` for PHP command? Like:
`/usr/local/bin/php -n ~/.composer/vendor/bin/php-cs-fixer`

**Comment by dbrent-amazon** [comment]
I had the same issue so I made /usr/local/bin/phpx with the following:

/usr/bin/env php -n "$@"

Set that in the php-cs-fixer for the php path. Don't forget to chmod +x the file.

**Comment by pfefferle** [comment]
@cxbig have you tried it with the example, @dbrent-amazon provided?

**Comment by cxbig** [comment]
@pfefferle 
Yes. Now I separated them into two scripts. `php` and `xphp`.
We can close this topic now.

**Comment by pfefferle** [comment]
thanks

**Comment by samuraii** [comment]
Could please anyone provide the exact command in terminal to solve this? Thanx
