### ISSUE TITLE
Loading a config file

### ISSUE THREAD

**Issue by ethanclevenger91** [pfefferle/atom-php-cs-fixer#28]
I can drop a `.php_cs` into the root of my project and this package will load it, which is great, but it'd be nice to have this set in a global fashion of sorts. Any ideas on how to accomplish that?

**Comment by pfefferle** [comment]
it is possible to add a settings field for that, but is this really a usecase? do you use custom settings that differs from the default PSR versions for a lot of different projects?

**Comment by ethanclevenger91** [comment]
The biggest one that comes to mind for me is [Laravel](https://github.com/laravel/laravel). They're using [PSR-4 autoloading](https://laravel.com/docs/master/contributions#coding-style) standards which doesn't play nice with php-cs-fixer out of the box - it tries to change my namespaces from `app` to `App`. Not that that's a huge deal, but the rest of the directories in root are lowercase, so the consistency is nice.

**Comment by pfefferle** [comment]
OK, sounds legit :)

I think it would be best to provide a settings field for a global `.php_cs` file that will be overwritten by the `.php_cs` files directly in the project, so that you could define exceptions.

**Comment by ethanclevenger91** [comment]
Sounds perfect, thanks! Love this package, btw.

**Comment by Falc** [comment]
Many projects add their own .php_cs to ensure every contribution follows the same guidelines so it makes sense to give higher priority to those files at a project-level to prevent breaking everything.

In fact, PHP-CS-Fixer works that way. It looks first for a project .php_cs.

**Comment by pfefferle** [comment]
`.php_cs` files inside the project are already supported

**Comment by pfefferle** [comment]
added with v4.0.0
