### ISSUE TITLE
How to config atom-php-cs-fixer in order to get { in the same line of the function?

### ISSUE THREAD

**Issue by mappedinn** [pfefferle/atom-php-cs-fixer#32]
Hi,

How should I config `atom-php-cs-fixer` in order to get an php file like this:

```
class MyClass{
    public getId(){
        // ...
    }
}
```

I don't like that the code become like this after running `atom-php-cs-fixer`:

```
class MyClass
{
    public getId()
    {
        // ...
    }
}
```

**Comment by pfefferle** [comment]
This is a `php-cs-fixer` setting, have a look at their page: http://cs.sensiolabs.org

You can try adding `-braces` to the atom-php-cs-fixer `fixers` settings field or add a customized `.php_cs` file to the root of your project.

**Comment by mappedinn** [comment]
The documentation say that 

> braces [PSR-2]
> The body of each structure MUST be enclosed by braces. Braces should be properly placed. Body of braces should be properly indented.

Great! But, both examples I provided are properly indented.

Anyway, I tried both config in `atom-php-cs-fixer` by putting in field **fixers** these:
-  `fix,-braces`
-  `fix,braces`

For both config, there is no difference in the results after running `atom-php-cs-fixer`. Have I missed some thing?

**Comment by pfefferle** [comment]
Why `fix,-braces`? Try to use only `-braces`!

I tried it and it worked for me.

**Comment by mappedinn** [comment]
for me there is no difference!

Are your using `.php_cs`? If yes, please give me an example that deals with braces.

Thanks
