### ISSUE TITLE
Error message about loaded config.

### ISSUE THREAD

**Issue by vitalybaev** [pfefferle/atom-php-cs-fixer#35]
Hi, I'm using `php-cs-fixer` with Laravel project, and dropped my own `.php_cs` file to the project's root. All works fine, but after any fix Atom show an error message, that actually not error.
<img width="456" alt="2016-08-24 9 18 38" src="https://cloud.githubusercontent.com/assets/724423/17920251/6cd769bc-69e4-11e6-9370-a8a18c271ede.png">

**Comment by pfefferle** [comment]
Oh, this is no error, but an information and the color should be blue or green. You can disable it, by disabling "show notifications". Can you tell me which themes do you use? I will check why it shows up like an error instead of a notification.

**Comment by vitalybaev** [comment]
@pfefferle Thanks for the reply. But this notifications shows when `Show notifications` settings was turned off. When I turn it on, green notification also appears:
<img width="464" alt="2016-08-24 10 45 44" src="https://cloud.githubusercontent.com/assets/724423/17922485/507bbbe0-69f0-11e6-90fd-7095256e8eef.png">
I'm using `Spacegray Dark Neue` theme for both ui and syntax.

I guess it fired by this lines: [https://github.com/pfefferle/atom-php-cs-fixer/blob/master/lib/php-cs-fixer.coffee#L119](https://github.com/pfefferle/atom-php-cs-fixer/blob/master/lib/php-cs-fixer.coffee#L119)

**Comment by pfefferle** [comment]
Hmm, but it should be fired here https://github.com/pfefferle/atom-php-cs-fixer/blob/master/lib/php-cs-fixer.coffee#L116

Anyways, it is no "real" error and the fixer should work fine (does it?) and I will fix this asap.

Thanks for reporting it!

**Comment by vitalybaev** [comment]
Oh, sure, you right. Yes, fixer works fine, the only reason of reporting is annoying messages if run it on every file save.
I'm waiting for update. Thank you!

**Comment by pfefferle** [comment]
Hmmm, the problem is, that atom is interpreting this as an error...
