### ISSUE TITLE
PHP CSS Fixer

### ISSUE THREAD

**Issue by samusonak** [pfefferle/atom-php-cs-fixer#36]
It says
Could not find 'php-cs-fixer'. The program may not be installed.
whereas it has been installed

**Comment by edomato** [comment]
Hi @samusonak 

What version are you using?, in what operating system?, have you configured the path to the executable on the settings of this package?.

Greets

**Comment by pfefferle** [comment]
I will close this for now! Feel free to reopen it, if it is still a problem, but be sure to add some more informations like the PHP, PHP-CS-Fixer, Atom and PHP-CS-Fixer plugin versions.
