### ISSUE TITLE
Changes vendor namespace to lower case

### ISSUE THREAD

**Issue by colinajd** [pfefferle/atom-php-cs-fixer#41]
On MacOs Sierra 10.12.1
Atom 1.12.3
Plugin Version 2.5.9

Every time I fix a file it makes the vendor namespace lowercase.
So 'App\Something\Something'
Becomes 'app\Something\Something'

I can't tell if I just don't know what I'm doing or managed to changed the config files or something

**Comment by colinajd** [comment]
![image](https://cloud.githubusercontent.com/assets/14014211/20351483/e5231b9c-ac0a-11e6-8c03-4e3c6d75145d.png)

**Comment by pfefferle** [comment]
the plugin has no logic at all, it only calls the php-cs-fixer script with the parameters you set in the settings, so it seems to be a php-cs-fixer... but let me guess, your code is an a folder called `app` with a lowercase a... try to use a capital A... I am not 100% sure, but I think the fixer maps the classname/namespaces to the folder structure and this might be the "problem".

**Comment by colinajd** [comment]
Thanks for getting back to me, Ill look for the php-cs-fixer settings, just wasnt sure where the problem was, I guess php-cs-fixer isnt aware that you can have namespaces autoloaded with differing file structure names.
