### ISSUE TITLE
Doesn't work with PHP-CS-Fixer v2.0.0

### ISSUE THREAD

**Issue by ricpelo** [pfefferle/atom-php-cs-fixer#42]
PHP-CS-Fixer v2.0.0 was released some days ago:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases

Current atom-php-cs-fixer doesn't work with it. It throws the following error message:

```[Symfony\Component\Console\Exception\RuntimeException]
The "--level" option does not exist.

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--] []...
```

**Comment by kenntchan** [comment]
Hey, coincidentally I just sent a PR adding support for it. Check my [fork](https://github.com/kenntchan/atom-php-cs-fixer), you have to install it manually but it might work for you in the meantime.

**Comment by ricpelo** [comment]
Great, thank you!

**Comment by ricpelo** [comment]
How can I install it manually, by the way?

**Comment by pfefferle** [comment]
released a new version based on the changes of @kenntchan, you can simply run the update.

**Comment by ricpelo** [comment]
@pfefferle , thank you very much!

**Comment by MaxGiting** [comment]
This broke my atom package as I'm using PHP-CS-Fixer v1.12.14. It wouldn't work at all and gave no error messages.
I want to keep using that Major version though so I had to uninstall this package and reinstall it via the command line running.
`apm install php-cs-fixer@3.0.0`
To get the the v3.0.0 version I could use.

**Comment by pfefferle** [comment]
@MaxGiting sorry for that, I try to add a version check.
