### ISSUE TITLE
Allow risky doesn't appear to work

### ISSUE THREAD

**Issue by Indemnity83** [pfefferle/atom-php-cs-fixer#46]
If I add a risky rule to my .php_cs config; it doesn't seem to matter whether I check the allow risky option or not, I get an error that the allow risky rules were not allowed to run (missing --allow-risky option on command line). 

atom-php-cs-fixer 4.0.0
php-cs-fixer 2.0.0

**Comment by pfefferle** [comment]
The risky-setting will not be used if you have a `.php_cs(.dist)` file. Try to add `->setRiskyAllowed(true)` to your config.

**Comment by Indemnity83** [comment]
Ah, you are correct; didn't realize the setting wouldn't be used with the config. Thanks

**Comment by pfefferle** [comment]
no problem :)
