### ISSUE TITLE
using-cache option does not exist.

### ISSUE THREAD

**Issue by kehd07** [pfefferle/atom-php-cs-fixer#48]
[Symfony\Component\Console\Exception\RuntimeException]
The "--using-cache" option does not exist.

fix [--config CONFIG] [--config-file [CONFIG-FILE]] [--dry-run] [--level LEVEL] [--fixers FIXERS] [--diff] [--format FORMAT] [--] []

**Comment by kehd07** [comment]
luis@avila:~/dev/basecincuenta/magento_base50x/app/code/Cincuenta/StModa/Model/Config/Source$ /home/luis/.composer/vendor/bin/php-cs-fixer 
PHP CS Fixer version 1.12.4 by Fabien Potencier and Dariusz Ruminski

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  fix          Fixes a directory or a file
  help         Displays help for a command
  list         Lists commands
  readme       Generates the README content, based on the fix command help
  self-update  Update php-cs-fixer.phar to the latest stable version.
  selfupdate   Update php-cs-fixer.phar to the latest stable version.

**Comment by pfefferle** [comment]
The latest version of this plugin only supports php-cs-fixer >= 2.0.0
