### ISSUE TITLE
do not know why, byt php fixer crashing on every file save

### ISSUE THREAD

**Issue by n3on4s** [pfefferle/atom-php-cs-fixer#49]
Just updatet fresh version, and got this.
![image](https://cloud.githubusercontent.com/assets/19694051/21523237/fcdc48fa-cd14-11e6-96f0-57d71eaff189.png)

**Comment by pfefferle** [comment]
which version of php-cs-fixer do you use? this plugin requires at least v2.0.0!

**Comment by n3on4s** [comment]
Sorry, yes it was outdated, my bad. 
Than you for a fast response to my stupid question.

**Comment by pfefferle** [comment]
no problem :)
