### ISSUE TITLE
Error when saving...

### ISSUE THREAD

**Issue by mikeerickson** [pfefferle/atom-php-cs-fixer#50]
I have just installed this plugin, but am having an issue when saving files.

I have php-cs-fixer installed local to my project and I know it works as I can execute it via CLI

![image](https://cloud.githubusercontent.com/assets/183153/21533733/a1fa50b4-cd12-11e6-9ba7-3d59c5fa017e.png)

**Comment by pfefferle** [comment]
can you re-try it with the latest version

**Comment by pfefferle** [comment]
will close this for now... please re-open if it still exist.
