### ISSUE TITLE
There is a conflict between php-cs-fixer and php-debug on macOS

### ISSUE THREAD

**Issue by oknixus** [pfefferle/atom-php-cs-fixer#52]
There is an orginal php on macOS, but for installing php-debug, I had to installed another php.
The path of orginal php is /usr/bin/php, and the new installed one, its path is /usr/local/bin/php.
If I rename the new one, the php-debug doesn't work.
If I do nothing , the dear php-cs-fixer will show me something in the below pic : 
![image](https://cloud.githubusercontent.com/assets/4592706/21737922/01271ef2-d4b9-11e6-8f0e-911aac6cf195.png)

I want to do something with the orginal php, but I have not a permitted:
![image](https://cloud.githubusercontent.com/assets/4592706/21738021/5264c2aa-d4ba-11e6-9568-dde81503cb20.png)
Could you help me or should I submit this issue to php-debug ?

**Comment by pfefferle** [comment]
It seems to work without problems (first example), cause php-can-fixer seems to run properly, except the xdebug warning.

**Comment by pfefferle** [comment]
There is also a settings field to define the path to the php executable you prefer

**Comment by pfefferle** [comment]
There is also a settings field to define the path to the php executable you prefer

**Comment by oknixus** [comment]
@pfefferle Yes,it works. I see, I will submit this issue to php-debug. Thanks a lot.  Your answer just like lightning. Thanks.
