### ISSUE TITLE
Got error on saving file

### ISSUE THREAD

**Issue by lezhnev74** [pfefferle/atom-php-cs-fixer#55]
Hi! I just installed the plugin on my Atom editor and got this error on trying to use it:

![img](https://ftp.azureedge.net/files/2017-01-18_61atd.jpg)

Can you advice what should I fix to make it work?

**Comment by pfefferle** [comment]
have you installed the latest version of php-cs-fixer? this plugin needs at least v2.0.0.

**Comment by lezhnev74** [comment]
Oops, I had `1.13.1` :(
I've installed 2.0.0 and it worked!
Appreciate your quick help!
