### ISSUE TITLE
Why the indentation format doesn't work for class methods?

### ISSUE THREAD

**Issue by joseluisq** [pfefferle/atom-php-cs-fixer#57]
__Before:__

![image](https://cloud.githubusercontent.com/assets/1700322/22254652/837599b6-e255-11e6-91dc-73d010930037.png)

__After:__

![image](https://cloud.githubusercontent.com/assets/1700322/22254861/090334b2-e256-11e6-9bc1-53ab4b94f4ef.png)

Used:
- php-cs-fixer `2.0.0`
- atom-php-cs-fixer `4.1.0`
  - PHP-CS-Fixer Rules: @PSR2

**Comment by pfefferle** [comment]
I think this is a PHP-CS-Fixer problem. Have you tested it with the command line tool? Do you have the same problem?

**Comment by joseluisq** [comment]
I tested this using `php-cs-fixer` CLI v2.1.0 `--rules=@PSR2` and the issue persists. 
I opened an issue at https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2539

**Comment by joseluisq** [comment]
I will close this issue because it is related with [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2539).
