### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by mvasin** [pfefferle/atom-php-cs-fixer#58]
Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
Object.fix (/Users/mvasin/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:177:50)
atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix (/Users/mvasin/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:142:26)
CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
```

**Comment by Krasnov8953** [comment]
Argument to path.dirname must be a string

Object.dirname - /Users/krasnov/Downloads/Atom 2.app/Contents/Resources/app.asar/src/electron-shims.js:9:10
Object.fix - /Users/krasnov/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:177:50
atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix - /Users/krasnov/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:142:26
CommandRegistry.handleCommandEvent - /Users/krasnov/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:259:29
handleCommandEvent - /Users/krasnov/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:59
CommandRegistry.dispatch - /Users/krasnov/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:160:19

**Comment by ghost** [comment]
Argument to path.dirname must be a string
Report Issue
Object.dirname - C:\Users\TEMP.NC\AppData\Local\atom\app-1.17.0\resources\app\src\electron-shims.js:9:10
Object.fix - C:\Users\TEMP.NC\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:177:50
atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix - C:\Users\TEMP.NC\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:142:26
CommandRegistry.handleCommandEvent - <embedded>:18796:35
handleCommandEvent - <embedded>:18534:65
CommandRegistry.dispatch - <embedded>:18697:25

**Comment by apanasenkamaksim** [comment]
Object.dirname - C:\Users\buren\AppData\Local\atom\app-1.18.0\resources\app\src\electron-shims.js:9:10
Object.fix - C:\Users\buren\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:177:50
atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix - C:\Users\buren\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:142:26
CommandRegistry.handleCommandEvent - <embedded>:18904:35
handleCommandEvent - <embedded>:18642:65

**Comment by mariananassar** [comment]
Object.dirname - /opt/atom/resources/app.asar/src/electron-shims.js:9:10
Object.fix - /home/mnassar/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:177:50
atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix - /home/mnassar/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:142:26
CommandRegistry.handleCommandEvent - /opt/atom/resources/app.asar/src/command-registry.js:259:29
<unknown> - /opt/atom/resources/app.asar/src/command-registry.js:3:59
Object.didConfirmSelection - /opt/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29

**Comment by saji89** [comment]
This is what I got:

```
Object.dirname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10
Object.fix - /Users/username/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:177:50
<unknown> - /Users/username/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:150:28
Function.module.exports.Emitter.simpleDispatch - <embedded>:63093:20
Emitter.emit - <embedded>:63209:34
TextBuffer.saveAs - <embedded>:28587:26
```

**Comment by anish-cubet** [comment]
```
Object.dirname - /usr/share/atom/resources/app/src/electron-shims.js:9:10
Object.fix - /home/username/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:177:50
<unknown> - /home/username/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:150:28
Function.module.exports.Emitter.simpleDispatch - <embedded>:62314:20
Emitter.emit - <embedded>:62418:34
TextBuffer.saveAs - <embedded>:28438:26
```

**Comment by kendal-shaw** [comment]
`Object.dirname - C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\src\electron-shims.js:9:10
Object.fix - C:\Users\username\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:177:50
atom-workspace.subscriptions.add.atom.commands.add.php-cs-fixer:fix - C:\Users\username\.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:142:26
CommandRegistry.handleCommandEvent - <embedded>:18904:35
handleCommandEvent - <embedded>:18642:65
CommandRegistry.dispatch - <embedded>:18805:25`

**Comment by simonwinter** [comment]
Object.dirname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10
Object.fix - /Users/simonwinter/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:177:50
<unknown> - /Users/simonwinter/.atom/packages/php-cs-fixer/lib/php-cs-fixer.coffee:150:28
Function.module.exports.Emitter.simpleDispatch - <embedded>:63093:20
Emitter.emit - <embedded>:63209:34
TextBuffer.saveAs - <embedded>:28587:26
