### ISSUE TITLE
No reaction on Windows

### ISSUE THREAD

**Issue by Dgame** [pfefferle/atom-php-cs-fixer#6]
Hi, I'm using your plugin on Windows 8.1 with Atom. If I call it directly from the console it works fine, but in Atom I get no reaction at all. My Executable Path is `C:/Users/Bjarne/Documents/php-cs-fixer.phar`

**Comment by Dgame** [comment]
To be more concrete, this is what I have in the input field: `php C:/Users/Bjarne/Documents/php-cs-fixer.phar`

**Comment by pfefferle** [comment]
is `php C:/Users/Bjarne/Documents/php-cs-fixer.phar` working in the console?

**Comment by Dgame** [comment]
Yes

**Comment by Dgame** [comment]
I tried it on my other PC. This works (in the console):

> E:\xampp\htdocs>php E:\xampp\htdocs\php-cs-fixer.phar fix test3.php --level=psr2

But this path in Atom:

> php E:\xampp\htdocs\php-cs-fixer.phar

did not.

**Comment by Dgame** [comment]
I see this error if I open the console:

> Die Syntax f�r den Dateinamen, Verzeichnisnamen oder die Datentr�gerbezeichnung ist falsch.
> C:\Users\Randy.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:75 stderrC:\Users\Randy\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:85 (anonymous function)events.js:77 emitOneevents.js:166 emit_stream_readable.js:146 readableAddChunk_stream_readable.js:109 Readable.pushnet.js:517 onread
> C:\Users\Randy.atom\packages\php-cs-fixer\lib\php-cs-fixer.coffee:78 php E:\xampp\htdocs\php-cs-fixer.phar exited with code: 1

**Comment by pfefferle** [comment]
Oh, ein Landsmann ;)

Danke für dein Feedback!

But let's switch to english, because others might have the same problem. You should also add the complete path to the `PHP.exe`. I am a Mac User but I tried it in a Windows VM yesterday and got it nearly working... I got no errors, but Atom seems to crop the params and calls the php-cs-fixer.phar without any of them... this means that the debug console only prints the help screen and the fixer terminates without doing anything...

I will take a deeper look at this, this weekend.

**Comment by Dgame** [comment]
Ah, auch ein Deutscher, trifft sich selten. :)

I tried your suggestions, so I changed my executable path to this `E:\xampp\php\php.exe E:\xampp\htdocs\php-cs-fixer.phar` but the error remains the same. :/ I also tried your older version with spawn, there I got at least a tool tip with an error, but it does not work too.

**Comment by pfefferle** [comment]
OK, then try to remove the PHP at all, just use the `.phar` file. You can open the debug console by pressing `strg + alt + i` btw.

**Comment by Dgame** [comment]
I already tried that too. You see the usage output from php-cs-fixer:

``````
PHP CS Fixer version 1.9 by Fabien Potencier (ef528b9)

Usage:
  command [options] [arguments]


php-cs-fixer.coffee:61 Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output

php-cs-fixer.coffee:61       --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug


php-cs-fixer.coffee:61 Available commands:
  fix          Fixes a directory or a file
  help         Displays help for a command
  list         Lists commands
  readme       Generates the README content, based on the fix command help
  self-update  Update php-cs-fixer.phar to the latest version.

php-cs-fixer.coffee:61   selfupdate   Update php-cs-fixer.phar to the latest version.

php-cs-fixer.coffee:63 E:\xampp\htdocs\php-cs-fixer.phar exited with code: 0```
``````

**Comment by pfefferle** [comment]
That is the same problem I had... That means that the fixer is called properly, but without any params...

**Comment by Dgame** [comment]
I tried everything I could (I editied the whole `php-cs-fixer.coffee` file). The problem is the BufferedProcess, for some strange reason my file has the wrong name. I tried back- and normal Slashes, no difference. If I call only `php` it works and if I call only `php-cs-fixer.phar` it works too, but it seems both combined does not work.

**Comment by pfefferle** [comment]
I located the problem... I had to add PHP as extra settings field and as main command, than it also works on Windows... Will update the plugin later today... thanks for your help and the debugging :)

**Comment by pfefferle** [comment]
Here are my changes if you can't wait ;) https://gist.github.com/pfefferle/b5be34ea616253063331

**Comment by Dgame** [comment]
I got no errors, but instead I got this `Could not open input file: php E:\xampp\htdocs\php-cs-fixer.phar`

**Comment by pfefferle** [comment]
Try to add the full path to the php file

**Comment by Dgame** [comment]
Never mind, without `php` in the path it works! Great, thank you very much.

**Comment by rugk** [comment]
(Ich treffe auch mal dazu... :smile: )

In my case it still does not work in Atom, but if I call it manually...

See the gif for details:
![php-cs-fixer_notworking](https://cloud.githubusercontent.com/assets/11966684/9233357/dd430048-4132-11e5-9667-03cb92ca0cb1.gif)

Windows 7
2.30
Atom 1.0.6

**Comment by rienheuver** [comment]
I think this introduced a bug on Linux. I now get the error 'Could not open input file: php-cs-fixer', probably because the plugin is calling php-cs-fxier through php. I.e.:
php php-cs-fixer
instead of
php-cs-fixer

The latter one works in my terminal though, the first one indeed gives the error the plugin serves me as well.

**Comment by mappedinn** [comment]
:+1: 

So, any update on this ofr Linux users?

**Comment by rugk** [comment]
:penguin: broken after :black_square_button: got fixed. That's not nice...

**Comment by mappedinn** [comment]
have a look on https://github.com/pfefferle/atom-php-cs-fixer/issues/31

Use a phar file and avoid the `~`
