### ISSUE TITLE
Only running once per "save"?

### ISSUE THREAD

**Issue by futuretechmag** [pfefferle/atom-php-cs-fixer#61]
So I been tinkering with the latest versions of Atom, PHP-CS and PHP-CS-Fixer.

First, by just using those 3 and no other packages I was getting deprecated warnings. I installed linter and linter-phpcs, and php-cs-fixer stopped getting flagged as deprecated?

Onto the real issue though, and perhaps this is the point of it, but it seems like it only fixes on a saved file? As an example, I paste your example code, it  says "Fixed all files..." (blue boxes) but does absolutely nothing. **HOWEVER**, if I was to save the bad code, and then run php-cs-fixer, I get the blue and green box (and it actually fixes the code), all without leaving Atom/closing the files.

Is that expected functionality or should I be able to write some slop, and then "Run php-cs-fixer" and it should fix up any slop. Write some more slop, "Run php-cs-fixer" and it fixes, etc all without saving the file or leaving Atom?

**Comment by pfefferle** [comment]
Yes, this is the expected behaviour. The pluign runs the CLI command on the file handle, so it can only fix things that are saved to the file.
