### ISSUE TITLE
Could not open input file: php-cs-fixer

### ISSUE THREAD

**Issue by ryanrahman26** [pfefferle/atom-php-cs-fixer#63]
I installed php-cs-fixer from ATOM and installing php-cs-fixer from Composer. But when i try to active php-cs-fixer on php file, it show information like the screenshoot. Please help..

![php-cs-fixer1](https://cloud.githubusercontent.com/assets/20228877/26230746/63c86f42-3c75-11e7-81a1-a44f09b5e7a3.png)
![php-cs-fixer2](https://cloud.githubusercontent.com/assets/20228877/26230751/6b8ddb86-3c75-11e7-94bc-8426ff8048d5.png)

**Comment by anaspk** [comment]
Hello Ryan,

I am also facing this exact same issue. Were you able to fix it? If yes, then how?

**Comment by pjkaufman** [comment]
This error means that php-cs-fixer is unable to find your php-cs-fixer.phar or php.cs-fixer-v2.phar files. Try downloading the php-fixer-cs.phar file from the this website: http://cs.sensiolabs.org/#installation. Then find where the file is located and put that in your php-cs-fixer plugin setting for the php-fixer-cs.phar.

**Comment by 1298799999** [comment]
change "PHP-CS-fixer executable path" from: "default" to "/usr/local/bin/php-cs-fixer"

**Comment by IrfanKnowledge** [comment]
6. **Use this**:
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('somedir')
    ->notPath('src/Symfony/Component/Translation/Tests/fixtures/resources.php')
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
  //->setRules([
        //'@PSR2' => true,
        //'strict_param' => true,
        //'array_syntax' => ['syntax' => 'short'],
  //  ])
 //->setFinder($finder)
    //->setCacheFile(__DIR__.'/.php_cs.cache')
  ->setUsingCache(false)
  //->setCacheFile(__DIR__.'\.php_cs.cache')
;

7.  Then **It Works**.
8. About detail that code, you can see https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file

**Comment by khanks** [comment]
@ryanrahman26 , I really wish I had time to waste on stuff like this but I have **real** programming to do. So I can't waste time trying to find out why an installed package can't find it's own files. Thanks, though.
