### ISSUE TITLE
PHP CS Fixer work fine when save, but don't show errors on IDE

### ISSUE THREAD

**Issue by pablorsk** [pfefferle/atom-php-cs-fixer#67]
Version: 0.30.3

When I save PHP files, work fine Beaturifier. The errors are fixed. I post a screenshot:
![screenshot320](https://user-images.githubusercontent.com/938894/27519747-e73e8794-59d0-11e7-825d-6546edd6e3a9.png)

But my Atom never show errors. Any ideas?

**Comment by pjkaufman** [comment]
Have you ever encountered an error trying to change the file? If so, Could you give some detail on how the error was encountered?

**Comment by pablorsk** [comment]
Is possible do something like this? (this is a typescript linter)

![screenshot339](https://user-images.githubusercontent.com/938894/29216386-e403feb4-7e84-11e7-84af-436122505d37.png)

As you can see, IDE mark and report error while I typing. Not a just a automatic fixer when save.

**Comment by pfefferle** [comment]
php-cs-fixer is only a fixer and do not support error reportings... if you want to display errors, you have to install for example a linter...

**Comment by pjkaufman** [comment]
What are you trying to do with that code block?

**Comment by pablorsk** [comment]
any  
Any linter plugin that reads the `.php_cs.dist` file? For example [linter-phpcs
](https://atom.io/packages/linter-phpcs) reads codesniffer files.

**Comment by pjkaufman** [comment]
Turn on notifications setting for your php-cs-fixer if you are using atom. That helps solve some issues.

**Comment by pfefferle** [comment]
@pablorsk I don't think there is any...

**Comment by pjkaufman** [comment]
What language are you trying to find a linter for (i.e. php, is, etc.)?

_Sent from my Samsung SM-G930T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pablorsk** [comment]
@pjkaufman I try linter PHP (or find the correct package) but reading `.php_cs.dist` like eslint linter reads `.eslintrc.json` or sasslinter reads `.sass-lint.yml`

**Comment by pjkaufman** [comment]
If you are using php and you find an error, assuming the php linter doesn't work; you can search for a php syntax checker online and paste your code there. Is the php linter not working? Also what is string2 in your image? It doesn't seem to follow php syntax for a param.

_Sent from my Samsung SM-G930T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
