### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by adibhanna** [pfefferle/atom-php-cs-fixer#7]
i've installed this plugin, and configured phpcs, but it's not working at all

**Comment by pfefferle** [comment]
Can you provide some more informations, like your Operating System for example?

**Comment by SrgSteak** [comment]
Can't get it to work either. I get the error message: "Failed to spawn command php php-cs-fixer. Make sure php php-cs-fixer is installed and on your PATH".

the ~/.composer is part of my PATH and the terminal allows execution of php-cs-fixer anywhere i like.

Any ideas?

**Comment by andrefrcastro** [comment]
+1

Changed the executable path to `php-cs-fixer` (installed via brew) and does not work.
I can run `php-cs-fixer` on my terminal, but atom can´t:

> Failed to spawn command php-cs-fixer. Make sure php-cs-fixer is installed and on your PATH

**Comment by pfefferle** [comment]
I just published a new version that adds support for the phpExecutablePath, because Windows system do require it. Please update and try to use the complete path to the php-cs-fixer executable.

**Comment by gammamatrix** [comment]
@andrefrcastro, @SrgSteak to get it to work with brew, you need to `cat` the contents of the script installed with `brew install php-cs-fixer`:

### Check to see where it installed

``` sh
which php-cs-fixer

/usr/local/bin/php-cs-fixer
```

### Cat the script

``` sh
cat /usr/local/bin/php-cs-fixer

#!/bin/sh

/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/php-cs-fixer/1.8.1/libexec/php-cs-fixer.phar $*
```

### Paste the path for php-cs-fixer.phar in _Executable Path_

_Go back to settings in Atom for php-cs-fixer._

`/usr/local/Cellar/php-cs-fixer/1.8.1/libexec/php-cs-fixer.phar`

**FYI:** _PHP Executable Path_ is empty for my set up. I also installed PHP with brew.

Use the keystroke: `ctrl-cmd-s`

I hope this helps 8)

This works for me without errors.

**Comment by andrefrcastro** [comment]
@gammamatrix thanks for the workaround. It works.

**Comment by pfefferle** [comment]
@gammamatrix thanks a lot for the detailed HOWTO!

**Comment by gammamatrix** [comment]
@pfefferle No problem, should we put this in the FAQ?

**Comment by pfefferle** [comment]
Sure, good idea!
