### ISSUE TITLE
How to add options with params

### ISSUE THREAD

**Issue by cringerjs** [pfefferle/atom-php-cs-fixer#70]
How do you define options that have params?  For instance, if we want to set the array_syntax option to short?  There are many other options...

Do we have to use a config file for these settings and not set them within the package settings?

**Comment by pfefferle** [comment]
You can use this syntax:

```bash
$ php php-cs-fixer.phar fix /path/to/project --rules='{"concat_space": {"spacing": "none"}}'
```

or you have to use a `.php_cs` file and define it there.

**Comment by claytonrcarter** [comment]
Hi, I just fixed this very same problem by configuring the "PHP-CS-Fixer Rules" setting w/i Atom to `{"@PSR2": true, "array_syntax": {"syntax": "short"}}`. This still uses the `@PSR2` ruleset, but adds the `array_syntax` rule. I struggled w/ this for a bit until I read [this comment](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2716#issuecomment-296350523) over at [FriendsOfPHP/PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
