### ISSUE TITLE
Сould not find

### ISSUE THREAD

**Issue by ghost** [pfefferle/atom-php-cs-fixer#73]
Выдает ошибку 
![2018-01-30 15-37-39](https://user-images.githubusercontent.com/32243762/35564298-84f26a4e-05db-11e8-89e7-8e39afee77ed.png)
при этом приложение установлено, какие действия необходимы для корректной работы?
![2018-01-30 15-39-05](https://user-images.githubusercontent.com/32243762/35564334-a41d0640-05db-11e8-883f-d586291159b1.png)
![2018-01-30 16-36-47](https://user-images.githubusercontent.com/32243762/35564398-cac1d884-05db-11e8-9d77-f6eede751a2f.png)
?????

**Comment by pfefferle** [comment]
As you can see in the error message, the error is from `atom beautifier` not from the php-cs-fixer app:  https://atom.io/packages/atom-beautify

Both plugins are implementing the same functionality, so you only have to use one of them.
