### ISSUE TITLE
Using a custom ruleset

### ISSUE THREAD

**Issue by fede-green** [pfefferle/atom-php-cs-fixer#74]
Hello! 

first of all: thanks for this plugin that seems to make it possible to do exactly what i would like to! :)

my problem is though that i can't find a way of using the Drupal standard coding rules as settings. I installed everything following this: https://www.drupal.org/node/1419988 so that when i run 

```
phpcs -i
The installed coding standards are Zend, PSR2, PSR1, MySource, Squiz, PEAR, DrupalPractice and Drupal

```
it shows correctly that the Drupal coding standard rules are understood by phpcs. Now... how can i make php cs fixer use that ruleset?

thanks, 

federico

**Comment by pfefferle** [comment]
This is not PHPCS! 

The [php-cs-fixer](https://github.com/FriendsOfPhp/PHP-CS-Fixer) is a completely different project and it works a bit different.

Here is how you create a config file:

* https://github.com/FriendsOfPhp/PHP-CS-Fixer#config-file

And here is something about drupal:

* https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/136

**Comment by drupol** [comment]
If you want to use PHP-CS-Fixer in your Drupal project, use this package: https://packagist.org/packages/drupol/drupal-conventions
