### ISSUE TITLE
Remarks not shown in IDE

### ISSUE THREAD

**Issue by StephanSchrade** [pfefferle/atom-php-cs-fixer#75]
In your animated use case (GIF) you show that all the problems within that file are shown in the bottom area and are marked with a red dot.
On my computer this does not happen, but the file is changed (and saved :-( ) after starting the fix-Command.
So it looks like the phar file is working, but remarks are not shown.
- windows 7
- atom 1.29.0
- php-cs-fixer atom plugin 4.1.1 
- php cs fixer 2.12.2

**Comment by pfefferle** [comment]
This is not part of this plugin, this is only for visualization.
