### ISSUE TITLE
Run on save

### ISSUE THREAD

**Issue by arall** [pfefferle/atom-php-cs-fixer#8]
Which is the easiest way to run `php-cs-fixer:fix` command on every file save, instead of manually run `ctrl-cmd-s`?

**Comment by pfefferle** [comment]
Good idea! Will also add a flag to the options menu to dis/enable it.

**Comment by rugk** [comment]
What does this closing mean? You do not implement it?

If not you should leave the issue open until it's implemented. (it would also confuse the milestone system otherwise)

**Comment by pfefferle** [comment]
no, it means that I have implementied it! will release the update soon!

**Comment by rugk** [comment]
Ah so just the release wasn't out. Okay, so that's great. :+1:
