### ISSUE TITLE
Disable for projects

### ISSUE THREAD

**Issue by tillkruss** [pfefferle/atom-php-cs-fixer#83]
Some projects don't have a `.php_cs`, but the entire source code is still formatted.

Is there any way to disable this package for certain projects or folders?

**Comment by pfefferle** [comment]
Not yet, do you have a suggestion how to realize it?

**Comment by pfefferle** [comment]
I can add a setting to skip the fixer if there is no `.php_cs` file?

**Comment by tillkruss** [comment]
That would be amazing!

**Comment by deanc** [comment]
I am also encountering this issue today too. Would like to have that option :)

**Comment by tillkruss** [comment]
@pfefferle: Any update on this?

**Comment by tillkruss** [comment]
Thanks!

**Comment by pfefferle** [comment]
Dies it work like expected?

**Comment by tillkruss** [comment]
@pfefferle: Yes, works like a charm, but the blue notification is a bit annoying for every safe.
