### ISSUE TITLE
No results using in Windows 10

### ISSUE THREAD

**Issue by kiwi3685** [pfefferle/atom-php-cs-fixer#84]
php-cs-fixer package 4.1.1
Atom 1.47.0
PHP (v. 7.3.6) is installed in  Xampp.
php-cs-fixer.phar is v. 2.16.3

Installation of the package in Atom worked OK (it appears in menus etc.), but when I run it I get only this message in console:
_php-cs-fixer.coffee:173 c:\xampp\php\php.exe exited with code: 3221225477_

Atom config has this for settings:
  "php-cs-fixer":
    executablePath: "c:\\Users\\Nigel\\.atom\\packages\\php-cs-fixer\\php-cs-fixer.phar"
    phpExecutablePath: "c:\\xampp\\php\\php.exe"

These are definitely the correct file locations.

Can you suggest what I might be doing wrong, or missing?

**Comment by pfefferle** [comment]
Sorry, but I have no Windows to test the scenario, but perhaps this might help: https://stackoverflow.com/questions/1138269/apache-error-notice-parent-child-process-exited-with-status-3221225477-res

**Comment by kiwi3685** [comment]
Thanks for the quick reply. Unfortunately  that link has at least one "did not fix it for me" attached to every "I did this and it worked" :-)  I could spend a lifetime trying all the different possibilities.

However, trying easier random ideas I added a "-n" argument to the setting "Add PHP arguments". This completely excludes the php.ini file. I have no idea why, but it seems to have worked.

**Comment by pfefferle** [comment]
Do you have only one php.ini file, for cli and for Apache? Perhaps that’s why!

**Comment by kiwi3685** [comment]
Yes, it looks like that is the reason. Thanks again for the prompt help.

I shall close this issue.

**Comment by kiwi3685** [comment]
Solution found.
