### ISSUE TITLE
Release, please

### ISSUE THREAD

**Issue by cdaguerre** [pfefferle/atom-php-cs-fixer#86]
Hey @pfefferle, could you tag a release for the merged v3 support?

**Comment by ti0rafa** [comment]
Can we get the new version @pfefferle ??

**Comment by pfefferle** [comment]
done! v4.3.0 is released. sorry that it took so long :(

**Comment by ti0rafa** [comment]
I love this plugin but I was stuck using the previous version for some time. Thank you @pfefferle I can confirm is working properly.
