### ISSUE TITLE
Not doing anything on Windows?

### ISSUE THREAD

**Issue by GForceWeb** [pfefferle/atom-php-cs-fixer#9]
I've installed php, composer and php-cs-fixer on my windows installation as well as this plugin inside of atom.

Running the fixer doesn't produce any on-screen errors however no apparent fixing is visible either. In the Atom console I get:

```
php-cs-fixer Command php
php-cs-fixer Arguments ["C:\Users\Grant\AppData\Roaming\Composer\vendor\bin\php-cs-fixer", "fix", "C:\Users\Grant\Documents\Git\WP-Client-Feedback\feedback\feedback.php", "--level=psr2", "--fixers=extra_empty_lines"]
SRC_DIR="`pwd`"
cd "`dirname "$0"`"
cd "../fabpot/php-cs-fixer"
BIN_TARGET="`pwd`/php-cs-fixer"
cd "$SRC_DIR"
"$BIN_TARGET" "$@"

php exited with code: 0
```

**Comment by GForceWeb** [comment]
Nevermind, using the wrong path in settings. Should have been vendor\fabpot\php-cs-fixer inside the composer folder instead of vendor\bin

**Comment by 18steps** [comment]
Can confirm it should be the `.../composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer` file which has *no extension* and is *not executable* despite the settings asking for the php-cs-fixer *executable*

(It's actually a PHP file so I guess we could argue the definition of executable)

Suggest the text in the settings be changed as most Windows users understand executable to mean `exe` or `bat` files.
